defmodule :"Elixir.Shop.Repo.Migrations.Add-archivedAt-to-users" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :archived_at, :naive_datetime
    end

    create unique_index(:products, [:slug], name: "products_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:products, [:slug], name: "products_unique_slug_index")

    alter table(:users) do
      remove :archived_at
    end
  end
end
